### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by SKYRAKERONE** [MertCokelek/360-degree-EyeTracking#1]
Hello,Thanks for the code.
I copied the code as you did, but it didn't work.
Class repeats are displayed.
I hope you can help me. Thank you so much

**Comment by MertCokelek** [comment]
Hello, there was a mistake in naming. Sorry for not updating that part.
In the script, the filename should be the same as the class name. Can you try changing the class name to `EyeTrackerDataRecording`, or the filename to `DataRecording.cs`?

P.S. sorry for the late response, I did not get a notification for the issue.

**Comment by SKYRAKERONE** [comment]
Thanks for your reply, this problem has been solved. Thank you again。
